version: "3.7"

services:
  athens:
    image: gomods/athens:latest
    environment:
      ATHENS_STORAGE_TYPE: memory
    ports:
      - 3000:3000

  app:
    image: golang:1.13rc1-buster
    environment:
      GO111MODULE: "on"
      GOPROXY: http://athens:3000
    links:
      - athens
    ports:
      - 8080:8080
    working_dir: /go/src/app
    volumes:
      - .:/go/src/app
    command: go run main.go
