version: "3.7"

services:
  athens:
    image: gomods/athens:latest
    environment:
      ATHENS_STORAGE_TYPE: memory
    ports:
      - 3000:3000

  go-get:
    build:
      context: .
    environment:
      GOPROXY: "${GOPROXY}"
    links:
      - athens
    command: time go get -v ./...
